Update patch level to 4.19.311
xcp-ng-rpms/kernel-alt pull request #23
Opened 2024-04-29 08:54 UTC by rushikeshjadhav

This commit realigns the patches with main kernel of XCP-ng 8.3.

2024-05-07 08:14 UTC, tescande requested changes
Hi,

Here is a list of patches that you have commented out but that I did not find merged yet in 4.19.311.

```
0001-scsi-libfc-retry-PRLI-if-we-cannot-analyse-the-paylo.patch
0001-dlm-don-t-allow-zero-length-names.patch
0001-dlm-NULL-check-before-some-freeing-functions-is-not-.patch
0001-fs-mark-expected-switch-fall-throughs.patch
0009-SUNRPC-Ensure-that-the-transport-layer-respect-major.patch
0011-SUNRPC-Start-the-first-major-timeout-calculation-at-.patch
0001-kernel-module.c-Only-return-EEXIST-for-modules-that-.patch
0001-xen-events-remove-event-handling-recursion-detection.patch
0006-tcp-add-tcp_sock_set_nodelay.patch
0007-sctp-add-sctp_sock_set_nodelay.patch
0009-dlm-dlm_internal-Replace-zero-length-array-with-flex.patch
0010-dlm-user-Replace-zero-length-array-with-flexible-arr.patch
0011-fs-dlm-remove-unneeded-semicolon-in-rcom.c.patch
0001-scsi-libfc-free-response-frame-from-GPN_ID.patch
0015-fs-dlm-set-skb-mark-for-listen-socket.patch
0016-fs-dlm-set-skb-mark-per-peer-socket.patch
0017-fs-dlm-don-t-close-socket-on-invalid-message.patch
0018-fs-dlm-change-handling-of-reconnects.patch
0019-fs-dlm-implement-tcp-graceful-shutdown.patch
0021-fs-dlm-synchronize-dlm-before-shutdown.patch
0022-fs-dlm-make-connection-hash-lockless.patch
0023-fs-dlm-fix-dlm_local_addr-memory-leak.patch
0025-fs-dlm-move-free-writequeue-into-con-free.patch
0026-fs-dlm-handle-possible-othercon-writequeues.patch
0027-fs-dlm-use-free_con-to-free-connection.patch
0028-fs-dlm-remove-lock-dependency-warning.patch
0029-fs-dlm-fix-mark-per-nodeid-setting.patch
0030-fs-dlm-handle-range-check-as-callback.patch
0031-fs-dlm-disallow-buffer-size-below-default.patch
0032-fs-dlm-rework-receive-handling.patch
0033-fs-dlm-fix-race-in-nodeid2con.patch
0034-fs-dlm-fix-proper-srcu-api-call.patch
0035-fs-dlm-define-max-send-buffer.patch
0036-fs-dlm-add-get-buffer-error-handling.patch
0037-fs-dlm-flush-othercon-at-close.patch
0038-fs-dlm-handle-non-blocked-connect-event.patch
0039-fs-dlm-add-helper-for-init-connection.patch
0040-fs-dlm-move-connect-callback-in-node-creation.patch
0041-fs-dlm-move-shutdown-action-to-node-creation.patch
0042-fs-dlm-refactor-sctp-sock-parameter.patch
0043-fs-dlm-listen-socket-out-of-connection-hash.patch
0044-fs-dlm-fix-check-for-multi-homed-hosts.patch
0045-fs-dlm-constify-addr_compare.patch
0046-fs-dlm-check-on-existing-node-address.patch
0001-xen-netback-avoid-race-in-xenvif_rx_ring_slots_avail.patch
0047-fs-dlm-fix-debugfs-dump.patch
0048-fs-dlm-fix-mark-setting-deadlock.patch
0049-fs-dlm-set-connected-bit-after-accept.patch
0050-fs-dlm-set-subclass-for-othercon-sock_mutex.patch
0051-fs-dlm-add-errno-handling-to-check-callback.patch
0052-fs-dlm-add-check-if-dlm-is-currently-running.patch
0053-fs-dlm-change-allocation-limits.patch
0054-fs-dlm-use-GFP_ZERO-for-page-buffer.patch
0055-fs-dlm-simplify-writequeue-handling.patch
0056-fs-dlm-check-on-minimum-msglen-size.patch
0057-fs-dlm-remove-unaligned-memory-access-handling.patch
0058-fs-dlm-flush-swork-on-shutdown.patch
0059-fs-dlm-add-shutdown-hook.patch
0060-fs-dlm-fix-missing-unlock-on-error-in-accept_from_so.patch
0061-fs-dlm-always-run-complete-for-possible-waiters.patch
0062-fs-dlm-add-dlm-macros-for-ratelimit-log.patch
0063-fs-dlm-fix-srcu-read-lock-usage.patch
0064-fs-dlm-set-is-othercon-flag.patch
0065-fs-dlm-reconnect-if-socket-error-report-occurs.patch
0067-fs-dlm-fix-connection-tcp-EOF-handling.patch
0068-fs-dlm-public-header-in-out-utility.patch
0069-fs-dlm-add-more-midcomms-hooks.patch
0070-fs-dlm-make-buffer-handling-per-msg.patch
0071-fs-dlm-add-functionality-to-re-transmit-a-message.patch
0072-fs-dlm-move-out-some-hash-functionality.patch
0073-fs-dlm-add-union-in-dlm-header-for-lockspace-id.patch
0074-fs-dlm-add-reliable-connection-if-reconnect.patch
0075-fs-dlm-add-midcomms-debugfs-functionality.patch
0076-fs-dlm-don-t-allow-half-transmitted-messages.patch
0077-fs-dlm-Fix-memory-leak-of-object-mh.patch
0078-fs-dlm-Fix-spelling-mistake-stucked-stuck.patch
0079-fs-dlm-fix-lowcomms_start-error-case.patch
0081-fs-dlm-use-alloc_ordered_workqueue.patch
0082-fs-dlm-move-dlm-allow-conn.patch
0083-fs-dlm-introduce-proto-values.patch
0084-fs-dlm-rename-socket-and-app-buffer-defines.patch
0085-fs-dlm-fix-race-in-mhandle-deletion.patch
0086-fs-dlm-invalid-buffer-access-in-lookup-error.patch
0087-fs-dlm-use-sk-sk_socket-instead-of-con-sock.patch
0088-fs-dlm-use-READ_ONCE-for-config-var.patch
0089-fs-dlm-fix-typo-in-tlv-prefix.patch
0090-fs-dlm-clear-CF_APP_LIMITED-on-close.patch
0091-fs-dlm-cleanup-and-remove-_send_rcom.patch
0092-fs-dlm-introduce-con_next_wq-helper.patch
0093-fs-dlm-move-to-static-proto-ops.patch
0094-fs-dlm-introduce-generic-listen.patch
0095-fs-dlm-auto-load-sctp-module.patch
0096-fs-dlm-generic-connect-func.patch
0097-fs-dlm-fix-multiple-empty-writequeue-alloc.patch
0098-fs-dlm-move-receive-loop-into-receive-handler.patch
0099-fs-dlm-implement-delayed-ack-handling.patch
0100-fs-dlm-fix-return-EINTR-on-recovery-stopped.patch
0101-fs-dlm-avoid-comms-shutdown-delay-in-release_lockspa.patch
0001-nbd-Fix-use-after-free-in-pid_show.patch
0001-fs-dlm-remove-check-SCTP-is-loaded-message.patch
0001-fs-dlm-let-handle-callback-data-as-void.patch
0001-fs-dlm-remove-double-list_first_entry-call.patch
0001-fs-dlm-don-t-call-kernel_getpeername-in-error_report.patch
0001-fs-dlm-replace-use-of-socket-sk_callback_lock-with-s.patch
0001-fs-dlm-fix-build-with-CONFIG_IPV6-disabled.patch
0001-fs-dlm-check-for-pending-users-filling-buffers.patch
0001-fs-dlm-remove-wq_alloc-mutex.patch
0001-fs-dlm-memory-cache-for-writequeue_entry.patch
0001-fs-dlm-memory-cache-for-lowcomms-hotpath.patch
0001-fs-dlm-print-cluster-addr-if-non-cluster-node-connec.patch
0001-dlm-uninitialized-variable-on-error-in-dlm_listen_fo.patch
0001-dlm-add-__CHECKER__-for-false-positives.patch
0001-fs-dlm-fix-grammar-in-lowcomms-output.patch
0001-fs-dlm-fix-race-in-lowcomms.patch
0001-fs-dlm-relax-sending-to-allow-receiving.patch
0001-fs-dlm-fix-sock-release-if-listen-fails.patch
0002-fs-dlm-retry-accept-until-EAGAIN-or-error-returns.patch
0003-fs-dlm-remove-send-repeat-remove-handling.patch
0001-nvme_fc-add-nvme_discovery-sysfs-attribute-to-fc-tra.patch
0001-nvme-fabrics-reject-I-O-to-offline-device.patch
0002-xen-netback-remove-unused-variables-pending_idx-and-.patch
0004-xen-netback-remove-not-needed-test-in-xenvif_tx_buil.patch
blkback-kthread-pid.patch
CA-285778-emulex-nic-ip-hdr-len.patch
call-kexec-before-offlining-noncrashing-cpus.patch
0002-xen-pciback-provide-a-reset-sysfs-file-to-try-harder.patch
pciback-disable-root-port-aer.patch
pciback-mask-root-port-comp-timeout.patch
sunrpc-force-disconnect-on-connection-timeout.patch
nfs-avoid-double-timeout.patch
bonding-balance-slb.patch
bridge-lock-fdb-after-garp.patch
kexec-reserve-crashkernel-region.patch
0001-arch-x86-xen-add-infrastruction-in-xen-to-support-gv.patch
0002-drm-i915-gvt-write-guest-ppgtt-entry-for-xengt-suppo.patch
0003-drm-i915-xengt-xengt-moudule-initial-files.patch
0004-drm-i915-xengt-check-on_destroy-on-pfn_to_mfn.patch
0005-arch-x86-xen-Import-x4.9-interface-for-ioreq.patch
0006-i915-gvt-xengt.c-Use-new-dm_op-instead-of-hvm_op.patch
0007-i915-gvt-xengt.c-New-interface-to-write-protect-PPGT.patch
0008-i915-gvt-xengt.c-Select-vgpu-type-according-to-low_g.patch
0009-drm-i915-gvt-Don-t-output-error-message-when-DomU-ma.patch
0010-drm-i915-gvt-xengt-Correctly-get-low-mem-max-gfn.patch
0011-drm-i915-gvt-Fix-dom0-call-trace-at-shutdown-or-rebo.patch
0012-hvm-dm_op.h-Sync-dm_op-interface-to-xen-4.9-release.patch
0013-drm-i915-gvt-Apply-g2h-adjust-for-GTT-mmio-access.patch
0014-drm-i915-gvt-Apply-g2h-adjustment-during-fence-mmio-.patch
0015-drm-i915-gvt-Patch-the-gma-in-gpu-commands-during-co.patch
0016-drm-i915-gvt-Retrieve-the-guest-gm-base-address-from.patch
0017-drm-i915-gvt-Align-the-guest-gm-aperture-start-offse.patch
0018-drm-i915-gvt-Add-support-to-new-VFIO-subregion-VFIO_.patch
0019-drm-i915-gvt-Implement-vGPU-status-save-and-restore-.patch
0020-vfio-Implement-n [...]

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Not Found in kernel tree
Not merged in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
>  #Merged Upstream
Not merged in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +Patch571: 0001-Add-auxiliary-bus-support.patch
For this series, it seems you have reverted `modpost: file2alias: go back to simple devtable lookup`, right ? I think it's better to adapt this patchset to use the devtable lookup as described [here](https://github.com/xcp-ng-rpms/kernel-alt/pull/21#issuecomment-2059277564).

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Merged Upstream
Not yet merged. Can be applied on top of 311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Merged Upstream
Not merged in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> -#Merged Upstream xengt
Not merged in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Patch119: 0001-kernel-module.c-Only-return-EEXIST-for-modules-that-.patch
This one still applies

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Patch8: 0001-scsi-libfc-retry-PRLI-if-we-cannot-analyse-the-paylo.patch
Not merged in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Patch49: 0001-dlm-don-t-allow-zero-length-names.patch
Not in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Patch55: 0001-dlm-NULL-check-before-some-freeing-functions-is-not-.patch
Not in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Patch83: 0001-fs-mark-expected-switch-fall-throughs.patch
Not in 4.19.311

2024-05-07 08:14 UTC, tescande commented on SPECS/kernel-alt.spec
> +#Introduced from Kernel repo
And should be included

2024-05-25 21:09 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Not Found in kernel tree
Added back.

2024-05-25 21:09 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
>  #Merged Upstream
This patch is already covered with modification in patch-4.19.287-288.

2024-05-25 21:09 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +Patch571: 0001-Add-auxiliary-bus-support.patch
Can be done however I tried to keep Citrix patches unmodified. This is in anticipation that Citrix will update them in future. The upstream kernel pq remains clean except one pq. If you still want to go ahead with modification then I'll keep both patches (upstream kernel and Citrix one) intact and add new small one to get desired result. Is that ok?

2024-05-25 21:09 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Merged Upstream
They are already active in pq. Do you mean to move them at the end of pq?

2024-05-25 21:10 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Merged Upstream
They are already active in pq. Unable to understand the requirement here. `dlm` is discussed separately in other comments on same PR.

2024-05-25 21:10 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> -#Merged Upstream xengt
They are already active in pq. Unable to understand the requirement here.
Ideally they are not required as `kernel-alt` does not support GVT.

2024-05-25 21:10 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Patch119: 0001-kernel-module.c-Only-return-EEXIST-for-modules-that-.patch
`0001-nbd-add-missing-config-put.patch` covered in patch-4.19.76-77
`0001-xen-pci-reserve-MCFG-areas-earlier.patch` covered in patch-4.19.78-79
`0001-kernel-module.c-Only-return-EEXIST-for-modules-that-.patch` covered in patch-4.19.64-65

2024-05-25 21:10 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Patch8: 0001-scsi-libfc-retry-PRLI-if-we-cannot-analyse-the-paylo.patch
Added back.

2024-05-25 21:10 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Patch49: 0001-dlm-don-t-allow-zero-length-names.patch
Relying on upstream kernel `dlm` as there are lot of conflicts between Citrix patches and upstream pq related to `dlm`. These `dlm` patches are going in 100s and affecting various patches from kernel tree. May be this needs more deliberation.

2024-05-25 21:11 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Patch55: 0001-dlm-NULL-check-before-some-freeing-functions-is-not-.patch
Relying on upstream kernel `dlm`.

2024-05-25 21:11 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Patch83: 0001-fs-mark-expected-switch-fall-throughs.patch
Added back.

2024-05-25 21:11 UTC, rushikeshjadhav commented on SPECS/kernel-alt.spec
> +#Introduced from Kernel repo
GFS2 was/is limited to Citrix Xenserver. IIRC XCP-ng does not offer it, so keeping these patches off to avoid conflicts with base kernel.

2024-05-25 21:13 UTC, rushikeshjadhav commented
> 0009-SUNRPC-Ensure-that-the-transport-layer-respect-major.patch
> 0011-SUNRPC-Start-the-first-major-timeout-calculation-at-.patch

Some patches such as SUNRPC can be applied when they are moved towards end of pq, however if we keep them at same position as Citrix kernel then it conflicts with upstream pq.

2024-05-25 21:14 UTC, rushikeshjadhav commented
> 0006-tcp-add-tcp_sock_set_nodelay.patch
> 0007-sctp-add-sctp_sock_set_nodelay.patch

Some patches like `0006-tcp-add-tcp_sock_set_nodelay.patch` and `0007-sctp-add-sctp_sock_set_nodelay.patch` are moved after upstream pq patch-4.19.51-52 however it looks like they have followups in Citrix kernel.

2024-05-25 21:15 UTC, rushikeshjadhav commented
> 0001-kernel-module.c-Only-return-EEXIST-for-modules-that-.patch

Found `0001-kernel-module.c-Only-return-EEXIST-for-modules-that-.patch` already included in patch-4.19.64-65

2024-05-25 21:15 UTC, rushikeshjadhav commented
> 0001-scsi-libfc-free-response-frame-from-GPN_ID.patch

Found `0001-scsi-libfc-free-response-frame-from-GPN_ID.patch` already included in patch-4.19.111-112

2024-05-25 21:16 UTC, rushikeshjadhav commented
> 0001-xen-netback-avoid-race-in-xenvif_rx_ring_slots_avail.patch

Found `0001-xen-netback-avoid-race-in-xenvif_rx_ring_slots_avail.patch` already included in patch-4.19.176-177

2024-05-25 21:16 UTC, rushikeshjadhav commented
> 0001-xen-events-remove-event-handling-recursion-detection.patch

Patch `0001-xen-events-remove-event-handling-recursion-detection.patch` is conflicting at its current position with patch-4.19.154-155

2024-05-25 21:17 UTC, rushikeshjadhav commented
> 0001-nbd-Fix-use-after-free-in-pid_show.patch

Patch `0001-nbd-Fix-use-after-free-in-pid_show.patch` is conflicting at its current position with patch-4.19.157-158 or at the end of pq. So need to identify correct position for it.

2024-05-25 21:17 UTC, rushikeshjadhav commented
> 0001-nvme_fc-add-nvme_discovery-sysfs-attribute-to-fc-tra.patch

Patch `0001-nvme_fc-add-nvme_discovery-sysfs-attribute-to-fc-tra.patch` is conflicting at its current position with patch-4.19.72-73

2024-05-25 21:18 UTC, rushikeshjadhav commented
> 0002-xen-netback-remove-unused-variables-pending_idx-and-.patch

Patch `0002-xen-netback-remove-unused-variables-pending_idx-and-.patch` is already covered by moving after patch-4.19.268-269

2024-05-25 21:18 UTC, rushikeshjadhav commented
> 0004-xen-netback-remove-not-needed-test-in-xenvif_tx_buil.patch

Patch `0004-xen-netback-remove-not-needed-test-in-xenvif_tx_buil.patch` is already covered upon moving at end of pq.

2024-05-25 21:18 UTC, rushikeshjadhav commented
> blkback-kthread-pid.patch

Patch `blkback-kthread-pid.patch` is already covered upon moving at end of pq.

2024-05-25 21:19 UTC, rushikeshjadhav commented
> CA-285778-emulex-nic-ip-hdr-len.patch

Patch `CA-285778-emulex-nic-ip-hdr-len.patch` is already covered with modification in patch-4.19.287-288.

2024-05-25 21:19 UTC, rushikeshjadhav commented
> 0002-xen-pciback-provide-a-reset-sysfs-file-to-try-harder.patch

Patch `0002-xen-pciback-provide-a-reset-sysfs-file-to-try-harder.patch` at its current position is failing for 1 out of 7 hunks

2024-05-25 21:20 UTC, rushikeshjadhav commented
> bonding-balance-slb.patch

Patch `bonding-balance-slb.patch` is conflicting at its current position with patch-4.19.102-103

2024-05-25 21:20 UTC, rushikeshjadhav commented
> bridge-lock-fdb-after-garp.patch

Patch `bridge-lock-fdb-after-garp.patch` is conflicting at its current position with patch-4.19.36-37

2024-05-25 21:20 UTC, rushikeshjadhav commented
> set-XENMEM_get_mfn_from_pfn-hypercall-number.patch

Patch `set-XENMEM_get_mfn_from_pfn-hypercall-number.patch` seems related to GVT

2024-05-25 21:21 UTC, rushikeshjadhav commented
> net-core__order-3_frag_allocator_causes_swiotlb_bouncing_under_xen.patch

Patch `net-core__order-3_frag_allocator_causes_swiotlb_bouncing_under_xen.patch` conflicts with patch-4.19.236-237 and may need small rewrite.

2024-10-11 08:49 UTC, stormi commented
This is now Done, albeit a bit differently.

2024-10-11 08:49 UTC, closed without merging